### ISSUE TITLE
Add option "Copy HTTP URL to this file"

### ISSUE THREAD

**Issue by llagerlof** [s-shin/atom-copy-path#1]
Would be very useful if we can have an option to copy a configurable HTTP path to the file.

We already have the option to copy the full path. eg:

```
L:\repository\project-trunk3\admin_page\manager\script\test_access.php
```

But to test manually the code I need to input this in browser:

```
http://1.2.3.4/myproject/admin_page/manager/script/test_access.php
```

Of course, it's necessary to exist an option somewhere we can define the new prefix (based on full path) "L:\repository\project-trunk3\" replaced by "http://1.2.3.4/myproject/" (and remaining backslashes replaced by slashes).

**Comment by s-shin** [comment]
Thank you for a suggestion!

I recognized the useful situation you mentioned, but I disagree to introduce the functionality.

There are two reasons I thought that:
1. The situation is rare in recent development using modern web application frameworks.
   In most of modern web application frameworks, end points are separated from file paths by a router.
2. I think `config.cson` should not contain settings of mapping paths to URLs because `config.cson` should be as portable as possible.
   The mapping is project specific settings, so the best way will be that it is put in the project root like .gitignore, package.json, .eslintrc etc.,
   but I'm not planing to make an original configuration file like them.

**Comment by llagerlof** [comment]
Ok, I understand your point. I will try to implement myself, thanks.
